# FreeBSD documentation

baseURL = "https://docs.freebsd.org/"
title = "FreeBSD Documentation Portal"
copyright = "BSD 2-clause 'Simplified' License"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
disablePathToLower = true
theme = "beastie"
disableKinds = [ "taxonomy" ]
authors = [ "carlavilla@FreeBSD.org" ]
ignoreFiles = [ "chapter.adoc$", "contrib-386bsd.adoc$", "contrib-additional.adoc$", "contrib-committers.adoc$", "contrib-corealumni.adoc$", "contrib-develalumni.adoc$", "contrib-develinmemoriam.adoc$", "contrib-portmgralumni.adoc$", "\\.po$" ]
enableRobotsTXT = true
enableGitInfo = true
timeout = "180s"

[params]
  websiteURL = "https://www.FreeBSD.org"
  description = "FreeBSD Documentation Portal"
  isOnline = true
  editBaseUrl = "https://github.com/freebsd/freebsd-doc/blob/main/documentation/content/"
  downloadBaseUrl = "https://download.freebsd.org/doc/"

[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ["^dart-sass-embedded$", "^go$", "^git$", "^npx$", "^postcss$", "^asciidoctor$"]
    osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|LOAD_PATH|RUBYLIB)$"]
  [security.funcs]
    getenv = ["^HUGO_"]
  [security.http]
    methods = ["(?i)GET|POST"]
    urls = [".*"]

[markup.asciidocExt]
    extensions = ["man-macro", "inter-document-references-macro", "cross-document-references-macro", "sectnumoffset-treeprocessor", "packages-macro", "git-macro"]
    [markup.asciidocExt.attributes]
      env-beastie = true
      isOnline = true
      skip-front-matter = true
      sectanchors = "after"

[outputs]
home = [ "HTML" ]
page = [ "HTML" ]
section = [ "HTML" ]
