name = "Beastie"
copyright = "BSD 2-clause 'Simplified' License"
description = "Theme to build the FreeBSD Documentation Portal"
homepage = "https://docs.FreeBSD.org"
tags = ["website", "freebsd", "bsd", "documentation"]
min_version = "0.146.0"

[author]
name = "Sergio Carlavilla"
homepage = "https://www.carlavilla.es"
