name = "Beastie"
copyright = "BSD 2-clause 'Simplified' License"
description = "Theme to build the FreeBSD website"
homepage = "https://www.freebsd.org"
tags = ["website", "freebsd", "bsd", "documentation"]
min_version = "0.70.0"

[author]
name = "Sergio Carlavilla"
homepage = "https://www.carlavilla.es"
repository = "https://www.gitlab.com/carlavilla"
